### ISSUE TITLE
Won't deploy

### ISSUE THREAD

**Issue by Riky4646** [Qrivi/Feednite#6]
Heroku says it can't find the buildpack to use

**Comment by Qrivi** [comment]
Can you give a bit more information? It looks to be a Heroku issue and not an issue with the codebase anyway but I can maybe help.

I just clicked the Deploy to Heroku button on the readme and after a minute [everything was up and running as expected](https://user-images.githubusercontent.com/3763638/127040133-9e26a8c8-558d-4df3-8493-1ebdafa67c33.png). Heroku should know which buildpack to use because of the `package.json` file in the root of the repo.

**Comment by Riky4646** [comment]
Heroku builds the app just fine, do i need to launch it on github to modify the language? because it's what i tried to do and it fails

**Comment by Qrivi** [comment]
You don't need to do anything to modify the language: when you load the page just add a `locale` parameter to the url. Make sure its value is set to how the locale is used on Epic's website (in their url), usually 2 lowercase letters. So for e.g. German add `locale=de`

**Comment by Qrivi** [comment]
Closing as this appears not to be an issue.
